import type { NextPage } from "next";
import Head from "next/head";

// styles
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../../styles/Home.module.css";
import Login from "../auth/Login";

const Home: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TrackiE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-5">
        <h1 className="text-center mt-5">Welcome to TrackiE</h1>
        <div className="max-w-xl m-0 m-auto text-sm">
          <p className="text-left mt-5">
            But I must explain to you how all this mistaken idea of denouncing
            pleasure and praising pain was born and I will give you a complete
            account of the system, and expound the actual teachings of the great
            explorer of the truth, the master-builder of human happiness.
          </p>
          <p className="text-left">
            No one rejects, dislikes, or avoids pleasure itself, because it is
            pleasure, but because those who do not know how to pursue pleasure
            rationally encounter consequences that are extremely painful. Nor
            again is there anyone who loves or pursues or desires to obtain pain
            of itself, because it is pain, but because occasionally
            circumstances occur in which toil and pain can procure him some
            great pleasure.
          </p>
        </div>
      </main>
      <Login />
    </div>
  );
};

export default Home;
